include current-theme.conf

enable_audio_bell no
remember_window_size no
remember_window_position no
shell_integration disabled
background_opacity 0.8
window_padding_width 16
confirm_os_window_close 0
#fonts
font_family JetBrainsMono Nerd Font Propr 
font_size 11

#cursor
cursor_shape block
cusor_block_interval 0
cursor_trail 3


#scrollbar
scrollbar never

#url
detect_urls yes
url_style curly

