###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = pkill rofi || ~/.config/rofi/launcher.sh
$browser = zen-browser
$reloadScript = ~/.config/hypr/script/reload.sh
